theme: jekyll-theme-cayman
title: web dev course
description: 
  - Become a web development.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - help/HELP.md
